name: mutiple shell commands

on:
  workflow_dispatch: 

jobs:
  blind:
    name: simple program
    runs-on: ubuntu-latest

    steps:
      - name: hello world
        run: echo "hello world"
  
      - name: change directory
        run: sudo su -

      - name: print files
        run: ls -la

      - name: change path
        run: cd /home/ubuntu
