name: sample workflow using variable and secrets
on:
    workflow_dispatch:

jobs:
    build:
        name: sample workflow using vars
        runs-on: ubuntu-latest
        steps:
            - name: print the variable
              run: |
                echo "${{ vars.MY_NAME }}"
                echo "HELLO WELCOME TO UK"
                echo "${{ secrets.AWS_ACCESS_KEY }}"
